# Generated by Django 5.1.7 on 2025-03-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('owner', models.CharField(max_length=50, verbose_name='Владелец')),
                ('token', models.CharField(max_length=250, verbose_name='Токен')),
            ],
            options={
                'verbose_name': 'Токен доступ',
                'verbose_name_plural': 'Токены доступа',
            },
        ),
    ]
