# Generated by Django 5.1.7 on 2025-03-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_primaryaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryaccess',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
    ]
