# Generated by Django 5.1.7 on 2025-03-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_primaryaccess_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='primaryaccess',
            options={'verbose_name': 'Токен доступа', 'verbose_name_plural': 'Токены доступа'},
        ),
        migrations.AddField(
            model_name='account',
            name='chat_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID чата'),
        ),
    ]
