# Generated by Django 5.1.6 on 2025-03-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(editable=False, max_length=128, verbose_name='Пароль'),
        ),
    ]
