# Generated by Django 5.1.6 on 2025-04-01 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infocard', '0009_remove_remember_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('limit', models.PositiveIntegerField(verbose_name='Максимальное количество карточек')),
                ('remember_count', models.PositiveIntegerField(verbose_name='Количество повторений на сегодня')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
            },
        ),
        migrations.CreateModel(
            name='RememberItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('index', models.PositiveIntegerField(default=0, verbose_name='Индекс')),
                ('remember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_items', to='infocard.remember', verbose_name='Повторение')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trainings.training', verbose_name='Тренировка')),
            ],
            options={
                'verbose_name': 'Повторение',
                'verbose_name_plural': 'Повторения',
            },
        ),
    ]
