# Generated by Django 5.1.6 on 2025-04-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rememberitem',
            name='index',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Индекс'),
        ),
    ]
