# Generated by Django 5.1.6 on 2025-04-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_alter_rememberitem_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='rememberitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
    ]
