# Generated by Django 5.1.6 on 2025-03-26 14:02

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infocard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remember',
            name='real_answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Реальный ответ'),
            preserve_default=False,
        ),
    ]
