# Generated by Django 5.1.6 on 2025-03-26 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infocard', '0004_alter_tag_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infocardtag',
            name='info_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_items', to='infocard.infocard'),
        ),
    ]
