# Generated by Django 5.1.6 on 2025-03-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infocard', '0005_alter_infocardtag_info_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='infocard',
            name='tags_text',
            field=models.CharField(default='', max_length=255, verbose_name='Теги'),
            preserve_default=False,
        ),
    ]
