# Generated by Django 5.1.6 on 2025-03-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infocard', '0006_infocard_tags_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='infocard',
            name='closed',
            field=models.BooleanField(default=True, verbose_name='Закрыто'),
        ),
    ]
