# Generated by Django 5.1.6 on 2025-04-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infocard', '0007_infocard_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remember',
            name='is_active',
        ),
        migrations.AddField(
            model_name='remember',
            name='day',
            field=models.DateField(blank=True, null=True, verbose_name='День'),
        ),
    ]
