# Generated by Django 5.1.6 on 2025-04-01 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infocard', '0008_remove_remember_is_active_remember_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remember',
            name='date',
        ),
    ]
